name = "BiochemicalAlgorithms"
uuid = "9d651bdf-8945-47d1-9188-34e269d8f7b5"
authors = ["Andreas Hildebrandt <andreas.hildebrandt@uni-mainz.de> and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BioStructures = "de9282ab-8554-53be-b2d6-f6c222edabfc"
BioSymbols = "3c28c6f8-a34d-59c4-9654-267d177fcfa9"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
BenchmarkTools = "1"
DataFrames = "1"
EnumX = "1"
JSON3 = "1"
NamedTupleTools = "0.14"
StaticArrays = "1"
StatsBase = "0.33"
StructTypes = "1"
Tables = "1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
