name = "BiochemicalAlgorithms"
uuid = "9d651bdf-8945-47d1-9188-34e269d8f7b5"
authors = ["Andreas Hildebrandt <andreas.hildebrandt@uni-mainz.de> and contributors"]
version = "0.1.0"

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
BioStructures = "de9282ab-8554-53be-b2d6-f6c222edabfc"
BioSymbols = "3c28c6f8-a34d-59c4-9654-267d177fcfa9"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CellListMap = "69e1c6dd-3888-40e6-b3c8-31ac5f578864"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
GraphDataFrameBridge = "3c71623a-a715-5176-9801-629b201a4880"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mendeleev = "c116f080-063d-490a-9873-2b5b2cce4c34"
MolecularGraph = "6c89ec66-9cd8-5372-9f91-fabc50dd27fd"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
AutoHashEquals = "0.2"
BioStructures = "1, 2"
BioSymbols = "4, 5"
DataFrames = "1"
DataFramesMeta = "0.12, 0.13, 0.14"
DataStructures = "0.18"
DocStringExtensions = "0.9"
EnumX = "1"
JSON3 = "1"
MolecularGraph = "0.13"
StaticArrays = "1"
StructTypes = "1"
Tables = "1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
ChainRulesTestUtils = "cdddcdb0-9152-4a09-a978-84456f9df70a"

[targets]
test = ["Test", "TestItemRunner", "ChainRulesTestUtils"]
