name = "BiochemicalAlgorithms"
uuid = "9d651bdf-8945-47d1-9188-34e269d8f7b5"
authors = ["Andreas Hildebrandt <andreas.hildebrandt@uni-mainz.de> and contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DataFrames = "1"
JSON3 = "1"
StaticArrays = "1"
Tables = "1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
