project:
  title: "BiochemicalAlgorithms.jl Tutorials"
  output-dir: ../docs/src/tutorials
  render:
    - "*.qmd"

fig-format: png

execute:
  freeze: auto
  eval: true
  echo: true
  output: true

format:
  commonmark:
    variant: -raw_html+pipe_tables+tex_math_dollars
    wrap: preserve

jupyter: julia-1.10
